version: "3.7"
services:
  postgres:
    image: postgres:12.4-alpine
    volumes:
      - ./docker/postgres/init_test_db.sql:/docker/entrypoint-initdb.d/init_test.db.sql
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics
      POSTGRES_DB: analytics

  redis:
    image: redis:6.0.8-alpine3.12
    volumes:
      - ./storage/redis:/data

  php:
    build: ./docker/php
    volumes:
    - .:/var/www/analytics/backend
    working_dir: /var/www/analytics/backend

  rabbitmq:
    image: rabbitmq:3.8.8-management-alpine
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./storage/rabbitmq:/var/lib/rabbitmq/mnesia

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - discovery.type=single-node
      - cluster.name=analytics-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./storage/elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  influxdb:
    image: influxdb:1.8.2-alpine
    volumes:
      - ./storage/influxdb:/var/lib/influxdb
      - ./docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      INFLUXDB_DB: analytics
      INFLUXDB_ADMIN_USER: 'admin'
      INFLUXDB_ADMIN_PASSWORD: 'analytics'
      INFLUXDB_USER: 'analytics'
      INFLUXDB_USER_PASSWORD: 'analytics'

  composer:
    build: ./docker/composer
    command: install
    volumes:
      - .:/app

  phpunit:
    build: ./docker/php
    command: vendor/bin/phpunit
    volumes:
      - .:/var/www/analytics/backend
    links:
      - postgres
      - elasticsearch
