version: "3.6"
services:
  postgres:
    image: postgres:11-beta2
    restart: always
    volumes:
      - ./docker/postgres/init_test_db.sql:/docker/entrypoint-initdb.d/init_test.db.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics
      POSTGRES_DB: analytics

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/analytics/backend
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./storage/logs:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
    - .:/var/www/analytics/backend
    working_dir: /var/www/analytics/backend

  rabbitmq:
    image: rabbitmq:3.7.7-management
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./storage/rabbitmq:/var/lib/rabbitmq/mnesia
    ports:
      - 15672:15672
      - 5672:5672

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    links:
      - postgres

  composer:
    build: ./docker/composer
    command: install
    volumes:
    - .:/app

#  phpunit:
#    build: ./docker/php
#    command: vendor/bin/phpunit
#    volumes:
#    - .:/var/www/analytics/backend