version: "3.7"
services:
  teamcity-server:
    image: jetbrains/teamcity-server
    ports:
      - "8112:8111"
    volumes:
      - ./storage/teamcity/data_dir:/data/teamcity_server/datadir
      - ./storage/teamcity/log_dir:/opt/teamcity/logs

  teamcity-agent:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://teamcity-server:8111
      - AGENT_NAME=regular_agent

  teamcity-minimal-agent:
    image: jetbrains/teamcity-minimal-agent
    environment:
      - SERVER_URL=http://teamcity-server:8111
      - AGENT_NAME=minimal_agent
